// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PediVax.BusinessObjects.DBContext;

#nullable disable

namespace PetVax.BusinessObjects.Migrations
{
    [DbContext(typeof(PetVaxContext))]
    [Migration("20250607041405_deploy-ver3")]
    partial class deployver3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PetVax.BusinessObjects.Models.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AccountId"));

                    b.Property<string>("AccessToken")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PasswordSalt")
                        .HasColumnType("text");

                    b.Property<string>("RefereshToken")
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("AccountId");

                    b.ToTable("Account", "dbo");

                    b.HasData(
                        new
                        {
                            AccountId = 1,
                            AccessToken = "",
                            CreatedAt = new DateTime(2025, 6, 7, 4, 14, 4, 682, DateTimeKind.Utc).AddTicks(5738),
                            CreatedBy = "system",
                            Email = "admin@petvax.com",
                            PasswordHash = "+2J1dugZ0Dups9Y/aP06rLEt3nLFKJnYl8GjzH+97vY=",
                            PasswordSalt = "jUI4XsK3J0RZFkbF4aND9zyqh1zmTjJzqkh48WuA6ag=",
                            RefereshToken = "",
                            Role = 1
                        },
                        new
                        {
                            AccountId = 2,
                            AccessToken = "",
                            CreatedAt = new DateTime(2025, 6, 7, 4, 14, 4, 682, DateTimeKind.Utc).AddTicks(5741),
                            CreatedBy = "system",
                            Email = "staff@petvax.com",
                            PasswordHash = "29BY7Et2vNL8N2mqXdg1GGNfzlnb+81w7U2WmzGEGoM=",
                            PasswordSalt = "Zve20x8V28J/EGCHU48DqLMNGe6cuUd4eYFvO88HkmI=",
                            RefereshToken = "",
                            Role = 2
                        });
                });

            modelBuilder.Entity("PetVax.BusinessObjects.Models.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AppointmentId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AppointmentCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("AppointmentStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<int>("PetId")
                        .HasColumnType("integer");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AppointmentId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PetId");

                    b.ToTable("Appointment", "dbo");
                });

            modelBuilder.Entity("PetVax.BusinessObjects.Models.AppointmentDetail", b =>
                {
                    b.Property<int>("AppointmentDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AppointmentDetailId"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AppointmentDetailCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("AppointmentId")
                        .HasColumnType("integer");

                    b.Property<int>("AppointmentStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Dose")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("HealthConditionId")
                        .HasColumnType("integer");

                    b.Property<int>("MicrochipItemId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("NextVaccinationInfo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PassportId")
                        .HasColumnType("integer");

                    b.Property<string>("Reaction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ServiceHistoryId")
                        .HasColumnType("integer");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VaccineBatchId")
                        .HasColumnType("integer");

                    b.Property<int>("VaccineProfileId")
                        .HasColumnType("integer");

                    b.Property<int>("VetId")
                        .HasColumnType("integer");

                    b.HasKey("AppointmentDetailId");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.HasIndex("HealthConditionId")
                        .IsUnique();

                    b.HasIndex("MicrochipItemId")
                        .IsUnique();

                    b.HasIndex("PassportId")
                        .IsUnique();

                    b.HasIndex("ServiceHistoryId");

                    b.HasIndex("VaccineBatchId")
                        .IsUnique();

                    b.HasIndex("VaccineProfileId");

                    b.HasIndex("VetId");

                    b.ToTable("AppointmentDetail", "dbo");
                });

            modelBuilder.Entity("PetVax.BusinessObjects.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CustomerId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("CurrentPoints")
                        .HasColumnType("text");

                    b.Property<string>("CustomerCode")
                        .HasColumnType("text");

                    b.Property<string>("DateOfBirth")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<int?>("MembershipId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("CustomerId");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.HasIndex("MembershipId")
                        .IsUnique();

                    b.ToTable("Customer", "dbo");
                });

            modelBuilder.Entity("PetVax.BusinessObjects.Models.Disease", b =>
                {
                    b.Property<int>("DiseaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DiseaseId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Symptoms")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Treatment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DiseaseId");

                    b.ToTable("Disease", "dbo");
                });

            modelBuilder.Entity("PetVax.BusinessObjects.Models.HealthCondition", b =>
                {
                    b.Property<int>("HealthConditionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HealthConditionId"));

                    b.Property<string>("Behavior")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BreathingRate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CheckDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Conclusion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConditionCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Different")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Digestion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EHNM")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Excrete")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HeartRate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<int>("PetId")
                        .HasColumnType("integer");

                    b.Property<string>("Psycho")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Respiratory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SkinAFur")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Temperature")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Weight")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("HealthConditionId");

                    b.HasIndex("PetId");

                    b.ToTable("HealthCondition", "dbo");
                });

            modelBuilder.Entity("PetVax.BusinessObjects.Models.Membership", b =>
                {
                    b.Property<int>("MembershipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MembershipId"));

                    b.Property<string>("Benefits")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MembershipCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MinPoints")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MembershipId");

                    b.ToTable("Membership", "dbo");
                });

            modelBuilder.Entity("PetVax.BusinessObjects.Models.Microchip", b =>
                {
                    b.Property<int>("MicrochipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MicrochipId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MicrochipCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MicrochipId");

                    b.ToTable("Microchip", "dbo");
                });

            modelBuilder.Entity("PetVax.BusinessObjects.Models.MicrochipItem", b =>
                {
                    b.Property<int>("MicrochipItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MicrochipItemId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("InstallationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MicrochipId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PetId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MicrochipItemId");

                    b.HasIndex("MicrochipId")
                        .IsUnique();

                    b.HasIndex("PetId");

                    b.ToTable("MicrochipItem", "dbo");
                });

            modelBuilder.Entity("PetVax.BusinessObjects.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("AppointmentDetailId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("PaymentCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VaccineId")
                        .HasColumnType("integer");

                    b.HasKey("PaymentId");

                    b.HasIndex("AppointmentDetailId")
                        .IsUnique();

                    b.HasIndex("CustomerId");

                    b.HasIndex("VaccineId");

                    b.ToTable("Payment", "dbo");
                });

            modelBuilder.Entity("PetVax.BusinessObjects.Models.Pet", b =>
                {
                    b.Property<int>("PetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PetId"));

                    b.Property<string>("Age")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("DateOfBirth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PetCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Weight")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("isSterilized")
                        .HasColumnType("boolean");

                    b.HasKey("PetId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Pet", "dbo");
                });

            modelBuilder.Entity("PetVax.BusinessObjects.Models.PetPassport", b =>
                {
                    b.Property<int>("PassportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PassportId"));

                    b.Property<DateTime>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ApprovedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HealthCheckDetails")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("HealthConditionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("IssuedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MicrochipItemId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("PassportCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PassportImage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PetId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VaccinationDetails")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("isRabiesVaccinated")
                        .HasColumnType("boolean");

                    b.HasKey("PassportId");

                    b.HasIndex("HealthConditionId");

                    b.HasIndex("MicrochipItemId");

                    b.HasIndex("PetId");

                    b.ToTable("PetPassport", "dbo");
                });

            modelBuilder.Entity("PetVax.BusinessObjects.Models.PointTransaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TransactionId"));

                    b.Property<string>("Change")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TransactionId");

                    b.HasIndex("CustomerId");

                    b.ToTable("PointTransaction", "dbo");
                });

            modelBuilder.Entity("PetVax.BusinessObjects.Models.ServiceHistory", b =>
                {
                    b.Property<int>("ServiceHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ServiceHistoryId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("ServiceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ServiceHistoryId");

                    b.ToTable("ServiceHistory", "dbo");
                });

            modelBuilder.Entity("PetVax.BusinessObjects.Models.VaccinationSchedule", b =>
                {
                    b.Property<int>("VaccinationScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VaccinationScheduleId"));

                    b.Property<int>("AgeInterval")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DiseaseId")
                        .HasColumnType("integer");

                    b.Property<int>("DoseNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("VaccinationScheduleId");

                    b.HasIndex("DiseaseId");

                    b.ToTable("VaccinationSchedule", "dbo");
                });

            modelBuilder.Entity("PetVax.BusinessObjects.Models.Vaccine", b =>
                {
                    b.Property<int>("VaccineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VaccineId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VaccineCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("VaccineId");

                    b.ToTable("Vaccine", "dbo");
                });

            modelBuilder.Entity("PetVax.BusinessObjects.Models.VaccineBatch", b =>
                {
                    b.Property<int>("VaccineBatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VaccineBatchId"));

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ManufactureDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("VaccineId")
                        .HasColumnType("integer");

                    b.HasKey("VaccineBatchId");

                    b.HasIndex("VaccineId");

                    b.ToTable("VaccineBatch", "dbo");
                });

            modelBuilder.Entity("PetVax.BusinessObjects.Models.VaccineDisease", b =>
                {
                    b.Property<int>("VaccineDiseaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VaccineDiseaseId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DiseaseId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<int>("VaccineId")
                        .HasColumnType("integer");

                    b.HasKey("VaccineDiseaseId");

                    b.HasIndex("DiseaseId");

                    b.HasIndex("VaccineId");

                    b.ToTable("VaccineDisease", "dbo");
                });

            modelBuilder.Entity("PetVax.BusinessObjects.Models.VaccineExport", b =>
                {
                    b.Property<int>("VaccineExportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VaccineExportId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExportCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExportDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("VaccineBatchId")
                        .HasColumnType("integer");

                    b.HasKey("VaccineExportId");

                    b.HasIndex("VaccineBatchId");

                    b.ToTable("VaccineExport", "dbo");
                });

            modelBuilder.Entity("PetVax.BusinessObjects.Models.VaccineExportDetail", b =>
                {
                    b.Property<int>("VaccineExportDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VaccineExportDetailId"));

                    b.Property<int>("AppointmentDetailId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("VaccineBatchId")
                        .HasColumnType("integer");

                    b.Property<int>("VaccineExportId")
                        .HasColumnType("integer");

                    b.HasKey("VaccineExportDetailId");

                    b.HasIndex("AppointmentDetailId")
                        .IsUnique();

                    b.HasIndex("VaccineBatchId");

                    b.HasIndex("VaccineExportId");

                    b.ToTable("VaccineExportDetail", "dbo");
                });

            modelBuilder.Entity("PetVax.BusinessObjects.Models.VaccineProfile", b =>
                {
                    b.Property<int>("VaccineProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VaccineProfileId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DiseaseId")
                        .HasColumnType("integer");

                    b.Property<string>("Dose")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("NextVaccinationInfo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PetId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PreferedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reaction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("VaccinationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("VaccinationScheduleId")
                        .HasColumnType("integer");

                    b.HasKey("VaccineProfileId");

                    b.HasIndex("DiseaseId");

                    b.HasIndex("PetId")
                        .IsUnique();

                    b.HasIndex("VaccinationScheduleId");

                    b.ToTable("VaccineProfile", "dbo");
                });

            modelBuilder.Entity("PetVax.BusinessObjects.Models.VaccineReceipt", b =>
                {
                    b.Property<int>("VaccineReceiptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VaccineReceiptId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReceiptCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ReceiptDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Suppiler")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("VaccineBatchId")
                        .HasColumnType("integer");

                    b.HasKey("VaccineReceiptId");

                    b.HasIndex("VaccineBatchId");

                    b.ToTable("VaccineReceipt", "dbo");
                });

            modelBuilder.Entity("PetVax.BusinessObjects.Models.VaccineReceiptDetail", b =>
                {
                    b.Property<int>("VaccineReceiptDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VaccineReceiptDetailId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("VaccineBatchId")
                        .HasColumnType("integer");

                    b.Property<int>("VaccineReceiptId")
                        .HasColumnType("integer");

                    b.HasKey("VaccineReceiptDetailId");

                    b.HasIndex("VaccineBatchId");

                    b.HasIndex("VaccineReceiptId");

                    b.ToTable("VaccineReceiptDetail", "dbo");
                });

            modelBuilder.Entity("PetVax.BusinessObjects.Models.Vet", b =>
                {
                    b.Property<int>("VetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VetId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VetCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("VetId");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("Vet", "dbo");
                });

            modelBuilder.Entity("PetVax.BusinessObjects.Models.VetSchedule", b =>
                {
                    b.Property<int>("VetScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VetScheduleId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("ScheduleDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SlotNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VetId")
                        .HasColumnType("integer");

                    b.HasKey("VetScheduleId");

                    b.HasIndex("VetId");

                    b.ToTable("VetSchedule", "dbo");
                });

            modelBuilder.Entity("PetVax.BusinessObjects.Models.Appointment", b =>
                {
                    b.HasOne("PetVax.BusinessObjects.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PetVax.BusinessObjects.Models.Pet", "Pet")
                        .WithMany("Appointments")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("PetVax.BusinessObjects.Models.AppointmentDetail", b =>
                {
                    b.HasOne("PetVax.BusinessObjects.Models.Appointment", "Appointment")
                        .WithOne()
                        .HasForeignKey("PetVax.BusinessObjects.Models.AppointmentDetail", "AppointmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PetVax.BusinessObjects.Models.HealthCondition", "HealthCondition")
                        .WithOne()
                        .HasForeignKey("PetVax.BusinessObjects.Models.AppointmentDetail", "HealthConditionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PetVax.BusinessObjects.Models.MicrochipItem", "MicrochipItem")
                        .WithOne()
                        .HasForeignKey("PetVax.BusinessObjects.Models.AppointmentDetail", "MicrochipItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PetVax.BusinessObjects.Models.PetPassport", "PetPassport")
                        .WithOne()
                        .HasForeignKey("PetVax.BusinessObjects.Models.AppointmentDetail", "PassportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PetVax.BusinessObjects.Models.ServiceHistory", null)
                        .WithMany("AppointmentDetails")
                        .HasForeignKey("ServiceHistoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PetVax.BusinessObjects.Models.VaccineBatch", "VaccineBatch")
                        .WithOne()
                        .HasForeignKey("PetVax.BusinessObjects.Models.AppointmentDetail", "VaccineBatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PetVax.BusinessObjects.Models.VaccineProfile", "VaccineProfile")
                        .WithMany("AppointmentDetails")
                        .HasForeignKey("VaccineProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PetVax.BusinessObjects.Models.Vet", "Vet")
                        .WithMany("AppointmentDetails")
                        .HasForeignKey("VetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("HealthCondition");

                    b.Navigation("MicrochipItem");

                    b.Navigation("PetPassport");

                    b.Navigation("VaccineBatch");

                    b.Navigation("VaccineProfile");

                    b.Navigation("Vet");
                });

            modelBuilder.Entity("PetVax.BusinessObjects.Models.Customer", b =>
                {
                    b.HasOne("PetVax.BusinessObjects.Models.Account", "Account")
                        .WithOne()
                        .HasForeignKey("PetVax.BusinessObjects.Models.Customer", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetVax.BusinessObjects.Models.Membership", "Membership")
                        .WithOne("Customer")
                        .HasForeignKey("PetVax.BusinessObjects.Models.Customer", "MembershipId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Account");

                    b.Navigation("Membership");
                });

            modelBuilder.Entity("PetVax.BusinessObjects.Models.HealthCondition", b =>
                {
                    b.HasOne("PetVax.BusinessObjects.Models.Pet", "Pet")
                        .WithMany("HealthConditions")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("PetVax.BusinessObjects.Models.MicrochipItem", b =>
                {
                    b.HasOne("PetVax.BusinessObjects.Models.Microchip", "Microchip")
                        .WithOne()
                        .HasForeignKey("PetVax.BusinessObjects.Models.MicrochipItem", "MicrochipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PetVax.BusinessObjects.Models.Pet", null)
                        .WithMany("MicrochipItems")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Microchip");
                });

            modelBuilder.Entity("PetVax.BusinessObjects.Models.Payment", b =>
                {
                    b.HasOne("PetVax.BusinessObjects.Models.AppointmentDetail", "AppointmentDetail")
                        .WithOne()
                        .HasForeignKey("PetVax.BusinessObjects.Models.Payment", "AppointmentDetailId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PetVax.BusinessObjects.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PetVax.BusinessObjects.Models.Vaccine", "Vaccine")
                        .WithMany("Payments")
                        .HasForeignKey("VaccineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppointmentDetail");

                    b.Navigation("Customer");

                    b.Navigation("Vaccine");
                });

            modelBuilder.Entity("PetVax.BusinessObjects.Models.Pet", b =>
                {
                    b.HasOne("PetVax.BusinessObjects.Models.Customer", "Customer")
                        .WithMany("Pets")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("PetVax.BusinessObjects.Models.PetPassport", b =>
                {
                    b.HasOne("PetVax.BusinessObjects.Models.HealthCondition", "HealthCondition")
                        .WithMany()
                        .HasForeignKey("HealthConditionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PetVax.BusinessObjects.Models.MicrochipItem", "MicrochipItem")
                        .WithMany()
                        .HasForeignKey("MicrochipItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PetVax.BusinessObjects.Models.Pet", "Pet")
                        .WithMany("PetPassports")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HealthCondition");

                    b.Navigation("MicrochipItem");

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("PetVax.BusinessObjects.Models.PointTransaction", b =>
                {
                    b.HasOne("PetVax.BusinessObjects.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("PetVax.BusinessObjects.Models.VaccinationSchedule", b =>
                {
                    b.HasOne("PetVax.BusinessObjects.Models.Disease", "Disease")
                        .WithMany("VaccinationSchedules")
                        .HasForeignKey("DiseaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Disease");
                });

            modelBuilder.Entity("PetVax.BusinessObjects.Models.VaccineBatch", b =>
                {
                    b.HasOne("PetVax.BusinessObjects.Models.Vaccine", "Vaccine")
                        .WithMany("VaccineBatches")
                        .HasForeignKey("VaccineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Vaccine");
                });

            modelBuilder.Entity("PetVax.BusinessObjects.Models.VaccineDisease", b =>
                {
                    b.HasOne("PetVax.BusinessObjects.Models.Disease", "Disease")
                        .WithMany("VaccineDiseases")
                        .HasForeignKey("DiseaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PetVax.BusinessObjects.Models.Vaccine", "Vaccine")
                        .WithMany("VaccineDiseases")
                        .HasForeignKey("VaccineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Disease");

                    b.Navigation("Vaccine");
                });

            modelBuilder.Entity("PetVax.BusinessObjects.Models.VaccineExport", b =>
                {
                    b.HasOne("PetVax.BusinessObjects.Models.VaccineBatch", null)
                        .WithMany("VaccineExports")
                        .HasForeignKey("VaccineBatchId");
                });

            modelBuilder.Entity("PetVax.BusinessObjects.Models.VaccineExportDetail", b =>
                {
                    b.HasOne("PetVax.BusinessObjects.Models.AppointmentDetail", "AppointmentDetail")
                        .WithOne()
                        .HasForeignKey("PetVax.BusinessObjects.Models.VaccineExportDetail", "AppointmentDetailId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PetVax.BusinessObjects.Models.VaccineBatch", "VaccineBatch")
                        .WithMany()
                        .HasForeignKey("VaccineBatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PetVax.BusinessObjects.Models.VaccineExport", "VaccineExport")
                        .WithMany("VaccineExportDetails")
                        .HasForeignKey("VaccineExportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppointmentDetail");

                    b.Navigation("VaccineBatch");

                    b.Navigation("VaccineExport");
                });

            modelBuilder.Entity("PetVax.BusinessObjects.Models.VaccineProfile", b =>
                {
                    b.HasOne("PetVax.BusinessObjects.Models.Disease", "Disease")
                        .WithMany("VaccineProfiles")
                        .HasForeignKey("DiseaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PetVax.BusinessObjects.Models.Pet", "Pet")
                        .WithOne()
                        .HasForeignKey("PetVax.BusinessObjects.Models.VaccineProfile", "PetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PetVax.BusinessObjects.Models.VaccinationSchedule", null)
                        .WithMany("VaccineProfiles")
                        .HasForeignKey("VaccinationScheduleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Disease");

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("PetVax.BusinessObjects.Models.VaccineReceipt", b =>
                {
                    b.HasOne("PetVax.BusinessObjects.Models.VaccineBatch", null)
                        .WithMany("VaccineReceipts")
                        .HasForeignKey("VaccineBatchId");
                });

            modelBuilder.Entity("PetVax.BusinessObjects.Models.VaccineReceiptDetail", b =>
                {
                    b.HasOne("PetVax.BusinessObjects.Models.VaccineBatch", "VaccineBatch")
                        .WithMany()
                        .HasForeignKey("VaccineBatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PetVax.BusinessObjects.Models.VaccineReceipt", "VaccineReceipt")
                        .WithMany("VaccineReceiptDetails")
                        .HasForeignKey("VaccineReceiptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("VaccineBatch");

                    b.Navigation("VaccineReceipt");
                });

            modelBuilder.Entity("PetVax.BusinessObjects.Models.Vet", b =>
                {
                    b.HasOne("PetVax.BusinessObjects.Models.Account", "Account")
                        .WithOne()
                        .HasForeignKey("PetVax.BusinessObjects.Models.Vet", "AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("PetVax.BusinessObjects.Models.VetSchedule", b =>
                {
                    b.HasOne("PetVax.BusinessObjects.Models.Vet", "Vet")
                        .WithMany("VetSchedules")
                        .HasForeignKey("VetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Vet");
                });

            modelBuilder.Entity("PetVax.BusinessObjects.Models.Customer", b =>
                {
                    b.Navigation("Pets");
                });

            modelBuilder.Entity("PetVax.BusinessObjects.Models.Disease", b =>
                {
                    b.Navigation("VaccinationSchedules");

                    b.Navigation("VaccineDiseases");

                    b.Navigation("VaccineProfiles");
                });

            modelBuilder.Entity("PetVax.BusinessObjects.Models.Membership", b =>
                {
                    b.Navigation("Customer")
                        .IsRequired();
                });

            modelBuilder.Entity("PetVax.BusinessObjects.Models.Pet", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("HealthConditions");

                    b.Navigation("MicrochipItems");

                    b.Navigation("PetPassports");
                });

            modelBuilder.Entity("PetVax.BusinessObjects.Models.ServiceHistory", b =>
                {
                    b.Navigation("AppointmentDetails");
                });

            modelBuilder.Entity("PetVax.BusinessObjects.Models.VaccinationSchedule", b =>
                {
                    b.Navigation("VaccineProfiles");
                });

            modelBuilder.Entity("PetVax.BusinessObjects.Models.Vaccine", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("VaccineBatches");

                    b.Navigation("VaccineDiseases");
                });

            modelBuilder.Entity("PetVax.BusinessObjects.Models.VaccineBatch", b =>
                {
                    b.Navigation("VaccineExports");

                    b.Navigation("VaccineReceipts");
                });

            modelBuilder.Entity("PetVax.BusinessObjects.Models.VaccineExport", b =>
                {
                    b.Navigation("VaccineExportDetails");
                });

            modelBuilder.Entity("PetVax.BusinessObjects.Models.VaccineProfile", b =>
                {
                    b.Navigation("AppointmentDetails");
                });

            modelBuilder.Entity("PetVax.BusinessObjects.Models.VaccineReceipt", b =>
                {
                    b.Navigation("VaccineReceiptDetails");
                });

            modelBuilder.Entity("PetVax.BusinessObjects.Models.Vet", b =>
                {
                    b.Navigation("AppointmentDetails");

                    b.Navigation("VetSchedules");
                });
#pragma warning restore 612, 618
        }
    }
}
